stages:
    - prepare
    - build
    - upload

image: $CI_PROJECT_PATH_SLUG/$CI_COMMIT_REF_SLUG

docker:
    stage: prepare
    tags: [docker-shell]
    script: [docker build -t $CI_PROJECT_PATH_SLUG/$CI_COMMIT_REF_SLUG .]

build:
    stage: build
    script:
        - python3.6 setup.py bdist_wheel
    artifacts:
        paths: [dist]

upload:
    stage: upload
    script:
        - |
          { CODE=0; TWINE_PASSWORD=${LRB_PYPI_PASSWORD} TWINE_USERNAME=${LRB_PYPI_USERNAME} python3.6 -m twine upload --verbose --repository-url ${LBR_PYPI_REPOSITORY_URL} dist/* > output.txt || CODE=$?; }
        - if [[ $CODE -ne 0 ]]; then
        -    ERR_MSG=`cat output.txt | tail -n -1`
        -    |
             FILE_EXISTS='{"message":"Validation failed: File name has already been taken"}'
        -    if [[ "$ERR_MSG" != "$FILE_EXISTS" ]]; then
        -        exit 1
        -    fi
        - fi
    only: ['master']

variables:
    GIT_STRATEGY: clone
